# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/simon-hash/RootsRock42/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name

